name: GitHub Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v2

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: 📦 Install Dependencies
        run: npm install

      - name: 👷 Build website
        run: npm run build

      - name: 📥 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: chickensoft.games
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
