name: main

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v2

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: 📦 Install Dependencies
        run: yarn install --frozen-lockfile

      - name: ✨ Check Format
        run: yarn run format:check

      - name: 🧹 Lint
        run: yarn run lint

      # export repository secrets to .env file before building
      # we use secrets to store our twitter api auth so that the app can
      # embed tweets statically during the build.
      - name: 🔐 Export Secrets
        run: |
          touch .env
          echo "TWITTER_BEARER_TOKEN=$TWITTER_BEARER_TOKEN" >> .env

      - name: 👷 Build website
        run: yarn build
